server:
  port: 8084
  
spring:
  application:
    name: spring-jpa
    
 # Spring JDBC configuration
  datasource:
    url: jdbc:mysql://localhost:3306/livrariadb
    username: root
    password: root

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: none
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    