server:
  port: 9090

spring:
  cloud:
    config:
      allowOverride: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/mjr86/cloud-config/
          searchPaths: config/*       